//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistentModel))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(AddressMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("Address", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "Address", typeof(PersistentModel))]
	public partial class Address : PersistentModel
	{
		private static AddressMetadata _metaModel;
		partial void _initialize();
		static Address()
		{
			_metaModel = MetadataCache<AddressMetadata>.GetData(null);
		}
		public Address() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public Address(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(Address), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected Address(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass, params System.Object[] parameters) :
			base(lifetime, type, metaClass, parameters)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("city", typeof(String), Length=50, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String City
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.city);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.city, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("country", typeof(String), Length=50, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Country
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.country);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.country, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("email", typeof(String), Length=60, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Email
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.email);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.email, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("fax", typeof(String), Length=25, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Fax
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.fax);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.fax, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myModel", typeof(PersistentModel), DatabaseTypeName="PersistentModel")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public PersistentModel MyModel
		{
			get
			{
				return this.GetPropertyReference<PersistentModel>(_metaModel.metaClass, _metaModel.myModel);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myModel, value, false);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("phone", typeof(String), Length=25, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Phone
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.phone);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.phone, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("street", typeof(String), Length=50, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Street
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.street);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.street, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("webSite", typeof(String), Length=60, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Website
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.webSite);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.webSite, value);
			}
		}
	#endregion
	}

	public partial class AddressMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata city;
		internal JadeSoftware.Joob.PropertyMetadata country;
		internal JadeSoftware.Joob.PropertyMetadata email;
		internal JadeSoftware.Joob.PropertyMetadata fax;
		internal JadeSoftware.Joob.PropertyMetadata myModel;
		internal JadeSoftware.Joob.PropertyMetadata phone;
		internal JadeSoftware.Joob.PropertyMetadata street;
		internal JadeSoftware.Joob.PropertyMetadata webSite;

		private AddressMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public AddressMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(Address), "Address", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			city = metaClass.CheckProperty("city", typeof(String), 50);
			country = metaClass.CheckProperty("country", typeof(String), 50);
			email = metaClass.CheckProperty("email", typeof(String), 60);
			fax = metaClass.CheckProperty("fax", typeof(String), 25);
			myModel = metaClass.CheckProperty("myModel", typeof(PersistentModel));
			phone = metaClass.CheckProperty("phone", typeof(String), 25);
			street = metaClass.CheckProperty("street", typeof(String), 50);
			webSite = metaClass.CheckProperty("webSite", typeof(String), 60);
		}
	}
}
