//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Address))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(AgentMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("Agent", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "Agent", typeof(PersistentModel))]
	public partial class Agent : PersistentModel
	{
		private static AgentMetadata _metaModel;
		partial void _initialize();
		static Agent()
		{
			_metaModel = MetadataCache<AgentMetadata>.GetData(null);
		}
		public Agent() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public Agent(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(Agent), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected Agent(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass, params System.Object[] parameters) :
			base(lifetime, type, metaClass, parameters)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myAddress", typeof(Address), DatabaseTypeName="Address")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Address MyAddress
		{
			get
			{
				return this.GetPropertyReference<Address>(_metaModel.metaClass, _metaModel.myAddress);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myAddress, value, true);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("name", typeof(String), Length=80, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Name
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.name);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.name, value);
			}
		}
	#endregion
	}

	public partial class AgentMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata myAddress;
		internal JadeSoftware.Joob.PropertyMetadata name;

		private AgentMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public AgentMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(Agent), "Agent", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			myAddress = metaClass.CheckProperty("myAddress", typeof(Address));
			name = metaClass.CheckProperty("name", typeof(String), 80);
		}
	}
}
