//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(CartItemsDict))]
	public partial class CartItemsDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _myItem = MetadataCache<CartItemsDictMetadata>.GetData(null).MyItemKey;

		public CartItemsDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_myItem})
		{
		}

		public CartItemsDictKey(Item myItem) :
				this()
		{
			this.MyItem = myItem;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("myItem", 0, typeof(Item), Length = 12, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public Item MyItem
		{
			get
			{
				return ((Item)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Item))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CartItem))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CartItemsDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CartItemsDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("CartItemsDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "CartItemsDict", typeof(MemberKeyDictionary<CartItemsDictKey, CartItem>), MembershipType=typeof(CartItem), Keys="myItem")]
	public partial class CartItemsDict : MemberKeyDictionary<CartItemsDictKey, CartItem>
	{

		private static CartItemsDictMetadata _metaModel;

		partial void Initialize();


		static CartItemsDict()
		{
			_metaModel = MetadataCache<CartItemsDictMetadata>.GetData(null);
		}

		public CartItemsDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Transient)
		{
		}

		public CartItemsDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(CartItemsDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected CartItemsDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual CartItem this[Item myItem]
		{
			get
			{
				CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
				 return base[_key_];
			}
			set
			{
				CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(Item myItem, out CartItem value)
		{
			CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(Item myItem, JadeSoftware.Joob.SearchStrategy strategy, out CartItem value)
		{
			CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<CartItemsDictKey, CartItem> StartingAtKey(Item myItem)
		{
			CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<CartItemsDictKey, CartItem> StartingAtKey(Item myItem, JadeSoftware.Joob.SearchStrategy strategy)
		{
			CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(Item myItem, CartItem value)
		{
			CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(Item myItem, CartItem value)
		{
			CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(Item myItem, CartItem value)
		{
			CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(Item myItem)
		{
			CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
			base.Remove(_key_);
		}

		public virtual void Remove(Item myItem, CartItem member)
		{
			CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
			base.Remove(_key_, member);
		}

		public virtual CartItem TryRemove(Item myItem)
		{
			CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(Item myItem, CartItem member)
		{
			CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(Item myItem, CartItem member)
		{
			CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(Item myItem)
		{
			CartItemsDictKey _key_ = new CartItemsDictKey(myItem);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Item))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CartItem))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CartItemsDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CartItemsDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("CartItemsDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class CartItemsDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : CartItem
	{

		private static CartItemsDictMetadata _metaModel;

		partial void Initialize();


		static CartItemsDict()
		{
			_metaModel = MetadataCache<CartItemsDictMetadata>.GetData(null);
		}

		protected CartItemsDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class CartItemsDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata MyItemKey;

		private CartItemsDictMetadata()
		{
		}

		public CartItemsDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			MetadataCache<ItemMetadata>.LoadData(null);
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(CartItemsDict), "CartItemsDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.MyItemKey = metaClass.CheckMemberKey(typeof(CartItemsDict), typeof(CartItem), "myItem", typeof(Item), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
