//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Item))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ShoppingCartTA))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CartItemMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("CartItem", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "CartItem", typeof(JoobObject))]
	public partial class CartItem : JoobObject
	{
		private static CartItemMetadata _metaModel;
		partial void _initialize();
		static CartItem()
		{
			_metaModel = MetadataCache<CartItemMetadata>.GetData(null);
		}
		public CartItem() :
			this(JadeSoftware.Joob.ClassPersistence.Transient)
		{
		}
		public CartItem(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(CartItem), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected CartItem(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass, params System.Object[] parameters) :
			base(lifetime, type, metaClass, parameters)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("code", typeof(String), Length=10, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Code
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.code);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.code, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myItem", typeof(Item), DatabaseTypeName="Item")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Item MyItem
		{
			get
			{
				return this.GetPropertyReference<Item>(_metaModel.metaClass, _metaModel.myItem);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myItem, value, false);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myShoppingCartTA", typeof(ShoppingCartTA), DatabaseTypeName="ShoppingCartTA")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public ShoppingCartTA MyShoppingCartTA
		{
			get
			{
				return this.GetPropertyReference<ShoppingCartTA>(_metaModel.metaClass, _metaModel.myShoppingCartTA);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myShoppingCartTA, value, false);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("offer", typeof(Decimal), Precision=12, Scale=2, DatabaseTypeName="Decimal")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Decimal Offer
		{
			get
			{
				return this.GetPropertyDecimal(_metaModel.metaClass, _metaModel.offer);
			}
			set
			{
				this.SetPropertyDecimal(_metaModel.metaClass, _metaModel.offer, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("transaction", typeof(String), Length=30, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Transaction
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.transaction);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.transaction, value);
			}
		}
	#endregion
	}

	public partial class CartItemMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata code;
		internal JadeSoftware.Joob.PropertyMetadata myItem;
		internal JadeSoftware.Joob.PropertyMetadata myShoppingCartTA;
		internal JadeSoftware.Joob.PropertyMetadata offer;
		internal JadeSoftware.Joob.PropertyMetadata transaction;

		private CartItemMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public CartItemMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(CartItem), "CartItem", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			code = metaClass.CheckProperty("code", typeof(String), 10);
			myItem = metaClass.CheckProperty("myItem", typeof(Item));
			myShoppingCartTA = metaClass.CheckProperty("myShoppingCartTA", typeof(ShoppingCartTA));
			offer = metaClass.CheckProperty("offer", typeof(Decimal), 12, 2);
			transaction = metaClass.CheckProperty("transaction", typeof(String), 30);
		}
	}
}
