//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(ClientsByNameDict))]
	public partial class ClientsByNameDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _name = MetadataCache<ClientsByNameDictMetadata>.GetData(null).NameKey;

		public ClientsByNameDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_name})
		{
		}

		public ClientsByNameDictKey(String name) :
				this()
		{
			this.Name = name;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("name", 0, typeof(String), Length = 80, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String Name
		{
			get
			{
				return ((String)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Client))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientsByNameDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ClientsByNameDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ClientsByNameDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "ClientsByNameDict", typeof(MemberKeyDictionary<ClientsByNameDictKey, Client>), MembershipType=typeof(Client), Keys="name")]
	public partial class ClientsByNameDict : MemberKeyDictionary<ClientsByNameDictKey, Client>
	{

		private static ClientsByNameDictMetadata _metaModel;

		partial void Initialize();


		static ClientsByNameDict()
		{
			_metaModel = MetadataCache<ClientsByNameDictMetadata>.GetData(null);
		}

		public ClientsByNameDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public ClientsByNameDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(ClientsByNameDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected ClientsByNameDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual Client this[String name]
		{
			get
			{
				ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
				 return base[_key_];
			}
			set
			{
				ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(String name, out Client value)
		{
			ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(String name, JadeSoftware.Joob.SearchStrategy strategy, out Client value)
		{
			ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<ClientsByNameDictKey, Client> StartingAtKey(String name)
		{
			ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<ClientsByNameDictKey, Client> StartingAtKey(String name, JadeSoftware.Joob.SearchStrategy strategy)
		{
			ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(String name, Client value)
		{
			ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(String name, Client value)
		{
			ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(String name, Client value)
		{
			ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(String name)
		{
			ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
			base.Remove(_key_);
		}

		public virtual void Remove(String name, Client member)
		{
			ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
			base.Remove(_key_, member);
		}

		public virtual Client TryRemove(String name)
		{
			ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(String name, Client member)
		{
			ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(String name, Client member)
		{
			ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(String name)
		{
			ClientsByNameDictKey _key_ = new ClientsByNameDictKey(name);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Client))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientsByNameDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ClientsByNameDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ClientsByNameDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class ClientsByNameDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : Client
	{

		private static ClientsByNameDictMetadata _metaModel;

		partial void Initialize();


		static ClientsByNameDict()
		{
			_metaModel = MetadataCache<ClientsByNameDictMetadata>.GetData(null);
		}

		protected ClientsByNameDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class ClientsByNameDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata NameKey;

		private ClientsByNameDictMetadata()
		{
		}

		public ClientsByNameDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(ClientsByNameDict), "ClientsByNameDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.NameKey = metaClass.CheckMemberKey(typeof(ClientsByNameDict), typeof(Client), "name", typeof(String), 80, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
