//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(CommissionRatesByPercentDict))]
	public partial class CommissionRatesByPercentDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _percentage = MetadataCache<CommissionRatesByPercentDictMetadata>.GetData(null).PercentageKey;

		public CommissionRatesByPercentDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_percentage})
		{
		}

		public CommissionRatesByPercentDictKey(Decimal percentage) :
				this()
		{
			this.Percentage = percentage;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("percentage", 0, typeof(Decimal), Length = 5, CaseSensitive = true, Ascending = true, SortOrder = 0, Precision = 5, Scale = 2)]
		public Decimal Percentage
		{
			get
			{
				return ((Decimal)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CommissionRate))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CommissionRatesByPercentDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CommissionRatesByPercentDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("CommissionRatesByPercentDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "CommissionRatesByPercentDict", typeof(MemberKeyDictionary<CommissionRatesByPercentDictKey, CommissionRate>), MembershipType=typeof(CommissionRate), Keys="percentage")]
	public partial class CommissionRatesByPercentDict : MemberKeyDictionary<CommissionRatesByPercentDictKey, CommissionRate>
	{

		private static CommissionRatesByPercentDictMetadata _metaModel;

		partial void Initialize();


		static CommissionRatesByPercentDict()
		{
			_metaModel = MetadataCache<CommissionRatesByPercentDictMetadata>.GetData(null);
		}

		public CommissionRatesByPercentDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public CommissionRatesByPercentDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(CommissionRatesByPercentDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected CommissionRatesByPercentDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual CommissionRate this[Decimal percentage]
		{
			get
			{
				CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
				 return base[_key_];
			}
			set
			{
				CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(Decimal percentage, out CommissionRate value)
		{
			CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(Decimal percentage, JadeSoftware.Joob.SearchStrategy strategy, out CommissionRate value)
		{
			CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<CommissionRatesByPercentDictKey, CommissionRate> StartingAtKey(Decimal percentage)
		{
			CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<CommissionRatesByPercentDictKey, CommissionRate> StartingAtKey(Decimal percentage, JadeSoftware.Joob.SearchStrategy strategy)
		{
			CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(Decimal percentage, CommissionRate value)
		{
			CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(Decimal percentage, CommissionRate value)
		{
			CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(Decimal percentage, CommissionRate value)
		{
			CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(Decimal percentage)
		{
			CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
			base.Remove(_key_);
		}

		public virtual void Remove(Decimal percentage, CommissionRate member)
		{
			CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
			base.Remove(_key_, member);
		}

		public virtual CommissionRate TryRemove(Decimal percentage)
		{
			CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(Decimal percentage, CommissionRate member)
		{
			CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(Decimal percentage, CommissionRate member)
		{
			CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(Decimal percentage)
		{
			CommissionRatesByPercentDictKey _key_ = new CommissionRatesByPercentDictKey(percentage);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CommissionRate))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CommissionRatesByPercentDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CommissionRatesByPercentDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("CommissionRatesByPercentDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class CommissionRatesByPercentDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : CommissionRate
	{

		private static CommissionRatesByPercentDictMetadata _metaModel;

		partial void Initialize();


		static CommissionRatesByPercentDict()
		{
			_metaModel = MetadataCache<CommissionRatesByPercentDictMetadata>.GetData(null);
		}

		protected CommissionRatesByPercentDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class CommissionRatesByPercentDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata PercentageKey;

		private CommissionRatesByPercentDictMetadata()
		{
		}

		public CommissionRatesByPercentDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(CommissionRatesByPercentDict), "CommissionRatesByPercentDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.PercentageKey = metaClass.CheckMemberKey(typeof(CommissionRatesByPercentDict), typeof(CommissionRate), "percentage", typeof(Decimal), 5, 2, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
