//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(AgentsByNameDict))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategory))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CommissionRateMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("CommissionRate", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "CommissionRate", typeof(PersistentModel))]
	public partial class CommissionRate : PersistentModel
	{
		private static CommissionRateMetadata _metaModel;
		partial void _initialize();
		static CommissionRate()
		{
			_metaModel = MetadataCache<CommissionRateMetadata>.GetData(null);
		}
		public CommissionRate() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public CommissionRate(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(CommissionRate), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected CommissionRate(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass, params System.Object[] parameters) :
			base(lifetime, type, metaClass, parameters)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allAgents", typeof(AgentsByNameDict), DatabaseTypeName="AgentsByNameDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public AgentsByNameDict AllAgents
		{
			get
			{
				return this.GetPropertyReference<AgentsByNameDict>(_metaModel.metaClass, _metaModel.allAgents);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myItemCategory", typeof(ItemCategory), DatabaseTypeName="ItemCategory")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public ItemCategory MyItemCategory
		{
			get
			{
				return this.GetPropertyReference<ItemCategory>(_metaModel.metaClass, _metaModel.myItemCategory);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myItemCategory, value, false);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("percentage", typeof(Decimal), Precision=5, Scale=2, DatabaseTypeName="Decimal")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Decimal Percentage
		{
			get
			{
				return this.GetPropertyDecimal(_metaModel.metaClass, _metaModel.percentage);
			}
			set
			{
				this.SetPropertyDecimal(_metaModel.metaClass, _metaModel.percentage, value);
			}
		}
	#endregion
	}

	public partial class CommissionRateMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata allAgents;
		internal JadeSoftware.Joob.PropertyMetadata myItemCategory;
		internal JadeSoftware.Joob.PropertyMetadata percentage;

		private CommissionRateMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public CommissionRateMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(CommissionRate), "CommissionRate", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			allAgents = metaClass.CheckProperty("allAgents", typeof(AgentsByNameDict));
			myItemCategory = metaClass.CheckProperty("myItemCategory", typeof(ItemCategory));
			percentage = metaClass.CheckProperty("percentage", typeof(Decimal), 5, 2);
		}
	}
}
