//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(AgentsByNameDict))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientsByNameDict))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CountriesByNameDict))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategoriesByNameDict))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategoriesByPrefixDict))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemsByNumberDict))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailItemsByGUIDDict))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesByItemDict))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderItemsByGUIDDict))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderItemsBySaleDateCodeDict))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TendersByTimeOfferDict))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Address))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CompanyMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("Company", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "Company", typeof(PersistentModel))]
	public partial class Company : PersistentModel
	{
		private static CompanyMetadata _metaModel;
		partial void _initialize();
		static Company()
		{
			_metaModel = MetadataCache<CompanyMetadata>.GetData(null);
		}
		public Company() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public Company(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(Company), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected Company(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass, params System.Object[] parameters) :
			base(lifetime, type, metaClass, parameters)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allAgents", typeof(AgentsByNameDict), DatabaseTypeName="AgentsByNameDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public AgentsByNameDict AllAgents
		{
			get
			{
				return this.GetPropertyReference<AgentsByNameDict>(_metaModel.metaClass, _metaModel.allAgents);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allClients", typeof(ClientsByNameDict), DatabaseTypeName="ClientsByNameDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public ClientsByNameDict AllClients
		{
			get
			{
				return this.GetPropertyReference<ClientsByNameDict>(_metaModel.metaClass, _metaModel.allClients);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allCountries", typeof(CountriesByNameDict), DatabaseTypeName="CountriesByNameDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public CountriesByNameDict AllCountries
		{
			get
			{
				return this.GetPropertyReference<CountriesByNameDict>(_metaModel.metaClass, _metaModel.allCountries);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allItemCategoriesByName", typeof(ItemCategoriesByNameDict), DatabaseTypeName="ItemCategoriesByNameDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public ItemCategoriesByNameDict AllItemCategoriesByName
		{
			get
			{
				return this.GetPropertyReference<ItemCategoriesByNameDict>(_metaModel.metaClass, _metaModel.allItemCategoriesByName);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allItemCategoriesByPrefix", typeof(ItemCategoriesByPrefixDict), DatabaseTypeName="ItemCategoriesByPrefixDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public ItemCategoriesByPrefixDict AllItemCategoriesByPrefix
		{
			get
			{
				return this.GetPropertyReference<ItemCategoriesByPrefixDict>(_metaModel.metaClass, _metaModel.allItemCategoriesByPrefix);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allItems", typeof(ItemsByNumberDict), DatabaseTypeName="ItemsByNumberDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public ItemsByNumberDict AllItems
		{
			get
			{
				return this.GetPropertyReference<ItemsByNumberDict>(_metaModel.metaClass, _metaModel.allItems);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allRetailItems", typeof(RetailItemsByGUIDDict), DatabaseTypeName="RetailItemsByGUIDDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public RetailItemsByGUIDDict AllRetailItems
		{
			get
			{
				return this.GetPropertyReference<RetailItemsByGUIDDict>(_metaModel.metaClass, _metaModel.allRetailItems);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allSalesByItem", typeof(SalesByItemDict), DatabaseTypeName="SalesByItemDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public SalesByItemDict AllSalesByItem
		{
			get
			{
				return this.GetPropertyReference<SalesByItemDict>(_metaModel.metaClass, _metaModel.allSalesByItem);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allTenderItems", typeof(TenderItemsByGUIDDict), DatabaseTypeName="TenderItemsByGUIDDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public TenderItemsByGUIDDict AllTenderItems
		{
			get
			{
				return this.GetPropertyReference<TenderItemsByGUIDDict>(_metaModel.metaClass, _metaModel.allTenderItems);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allTenderItemsBySaleDate", typeof(TenderItemsBySaleDateCodeDict), DatabaseTypeName="TenderItemsBySaleDateCodeDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public TenderItemsBySaleDateCodeDict AllTenderItemsBySaleDate
		{
			get
			{
				return this.GetPropertyReference<TenderItemsBySaleDateCodeDict>(_metaModel.metaClass, _metaModel.allTenderItemsBySaleDate);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allTenders", typeof(TendersByTimeOfferDict), DatabaseTypeName="TendersByTimeOfferDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public TendersByTimeOfferDict AllTenders
		{
			get
			{
				return this.GetPropertyReference<TendersByTimeOfferDict>(_metaModel.metaClass, _metaModel.allTenders);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myAddress", typeof(Address), DatabaseTypeName="Address")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Address MyAddress
		{
			get
			{
				return this.GetPropertyReference<Address>(_metaModel.metaClass, _metaModel.myAddress);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myAddress, value, true);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("name", typeof(String), Length=80, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Name
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.name);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.name, value);
			}
		}
	#endregion
	}

	public partial class CompanyMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata allAgents;
		internal JadeSoftware.Joob.PropertyMetadata allClients;
		internal JadeSoftware.Joob.PropertyMetadata allCountries;
		internal JadeSoftware.Joob.PropertyMetadata allItemCategoriesByName;
		internal JadeSoftware.Joob.PropertyMetadata allItemCategoriesByPrefix;
		internal JadeSoftware.Joob.PropertyMetadata allItems;
		internal JadeSoftware.Joob.PropertyMetadata allRetailItems;
		internal JadeSoftware.Joob.PropertyMetadata allSalesByItem;
		internal JadeSoftware.Joob.PropertyMetadata allTenderItems;
		internal JadeSoftware.Joob.PropertyMetadata allTenderItemsBySaleDate;
		internal JadeSoftware.Joob.PropertyMetadata allTenders;
		internal JadeSoftware.Joob.PropertyMetadata myAddress;
		internal JadeSoftware.Joob.PropertyMetadata name;

		private CompanyMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public CompanyMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(Company), "Company", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			allAgents = metaClass.CheckProperty("allAgents", typeof(AgentsByNameDict));
			allClients = metaClass.CheckProperty("allClients", typeof(ClientsByNameDict));
			allCountries = metaClass.CheckProperty("allCountries", typeof(CountriesByNameDict));
			allItemCategoriesByName = metaClass.CheckProperty("allItemCategoriesByName", typeof(ItemCategoriesByNameDict));
			allItemCategoriesByPrefix = metaClass.CheckProperty("allItemCategoriesByPrefix", typeof(ItemCategoriesByPrefixDict));
			allItems = metaClass.CheckProperty("allItems", typeof(ItemsByNumberDict));
			allRetailItems = metaClass.CheckProperty("allRetailItems", typeof(RetailItemsByGUIDDict));
			allSalesByItem = metaClass.CheckProperty("allSalesByItem", typeof(SalesByItemDict));
			allTenderItems = metaClass.CheckProperty("allTenderItems", typeof(TenderItemsByGUIDDict));
			allTenderItemsBySaleDate = metaClass.CheckProperty("allTenderItemsBySaleDate", typeof(TenderItemsBySaleDateCodeDict));
			allTenders = metaClass.CheckProperty("allTenders", typeof(TendersByTimeOfferDict));
			myAddress = metaClass.CheckProperty("myAddress", typeof(Address));
			name = metaClass.CheckProperty("name", typeof(String), 80);
		}
	}
}
