//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Agent))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Client))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Company))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemSearch))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ShoppingCartTA))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ErewhonModelSchemaAppMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ErewhonModelSchemaApp", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "ErewhonModelSchemaApp", typeof(JoobObject))]
	public partial class ErewhonModelSchemaApp : JoobObject
	{
		private static ErewhonModelSchemaAppMetadata _metaModel;
		partial void _initialize();
		static ErewhonModelSchemaApp()
		{
			_metaModel = MetadataCache<ErewhonModelSchemaAppMetadata>.GetData(null);
		}
		public ErewhonModelSchemaApp() :
			this(JadeSoftware.Joob.ClassPersistence.Transient)
		{
		}
		public ErewhonModelSchemaApp(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(ErewhonModelSchemaApp), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected ErewhonModelSchemaApp(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass, params System.Object[] parameters) :
			base(lifetime, type, metaClass, parameters)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myAgent", typeof(Agent), DatabaseTypeName="Agent")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Agent MyAgent
		{
			get
			{
				return this.GetPropertyReference<Agent>(_metaModel.metaClass, _metaModel.myAgent);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myAgent, value, false);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myClient", typeof(Client), DatabaseTypeName="Client")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Client MyClient
		{
			get
			{
				return this.GetPropertyReference<Client>(_metaModel.metaClass, _metaModel.myClient);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myClient, value, false);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myCompany", typeof(Company), DatabaseTypeName="Company")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Company MyCompany
		{
			get
			{
				return this.GetPropertyReference<Company>(_metaModel.metaClass, _metaModel.myCompany);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myCompany, value, false);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myShopItemSearch", typeof(ItemSearch), DatabaseTypeName="ItemSearch")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public ItemSearch MyShopItemSearch
		{
			get
			{
				return this.GetPropertyReference<ItemSearch>(_metaModel.metaClass, _metaModel.myShopItemSearch);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myShopItemSearch, value, false);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myShoppingCartTA", typeof(ShoppingCartTA), DatabaseTypeName="ShoppingCartTA")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public ShoppingCartTA MyShoppingCartTA
		{
			get
			{
				return this.GetPropertyReference<ShoppingCartTA>(_metaModel.metaClass, _metaModel.myShoppingCartTA);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myShoppingCartTA, value, false);
			}
		}
	#endregion
	
#region Jade Methods

		[JadeSoftware.Joob.Client.JoobMethodAttribute("setAgent")]
		public void SetAgent(Agent pAgent)
		{
			using (JadeParam jadeParam = new JadeParamObject(pAgent))
			{
				this.SendMessage(_metaModel.setAgent, null, jadeParam);
				return;
			}

		}

		[JadeSoftware.Joob.Client.JoobMethodAttribute("setClient")]
		public void SetClient(Client pClient)
		{
			using (JadeParam jadeParam = new JadeParamObject(pClient))
			{
				this.SendMessage(_metaModel.setClient, null, jadeParam);
				return;
			}

		}

		[JadeSoftware.Joob.Client.JoobMethodAttribute("setCompany")]
		public void SetCompany(Company @value)
		{
			using (JadeParam jadeParam = new JadeParamObject(@value))
			{
				this.SendMessage(_metaModel.setCompany, null, jadeParam);
				return;
			}

		}
	#endregion
	}

	public partial class ErewhonModelSchemaAppMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata myAgent;
		internal JadeSoftware.Joob.PropertyMetadata myClient;
		internal JadeSoftware.Joob.PropertyMetadata myCompany;
		internal JadeSoftware.Joob.PropertyMetadata myShopItemSearch;
		internal JadeSoftware.Joob.PropertyMetadata myShoppingCartTA;
		internal JadeSoftware.Joob.MethodMetadata setAgent;
		internal JadeSoftware.Joob.MethodMetadata setClient;
		internal JadeSoftware.Joob.MethodMetadata setCompany;

		private ErewhonModelSchemaAppMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public ErewhonModelSchemaAppMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(ErewhonModelSchemaApp), "ErewhonModelSchemaApp", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			myAgent = metaClass.CheckProperty("myAgent", typeof(Agent));
			myClient = metaClass.CheckProperty("myClient", typeof(Client));
			myCompany = metaClass.CheckProperty("myCompany", typeof(Company));
			myShopItemSearch = metaClass.CheckProperty("myShopItemSearch", typeof(ItemSearch));
			myShoppingCartTA = metaClass.CheckProperty("myShoppingCartTA", typeof(ShoppingCartTA));
			setAgent = metaClass.CheckMethod(metaClass,"setAgent");
			setClient = metaClass.CheckMethod(metaClass,"setClient");
			setCompany = metaClass.CheckMethod(metaClass,"setCompany");
		}
	}
}
