//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Address))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Agent))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CartItem))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Client))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CommissionRate))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Company))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CompanyTA))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Country))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Item))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategory))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemSearch))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Location))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ModelTA))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistentModel))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Region))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailItem))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailSale))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailSaleTA))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Sale))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ShoppingCartTA))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Tender))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderItem))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderSale))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderSaleTA))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderTA))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ErewhonObjectMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ErewhonObject", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "ErewhonObject", typeof(JoobObject))]
	public partial class ErewhonObject : JoobObject
	{
		private static ErewhonObjectMetadata _metaModel;
		partial void _initialize();
		static ErewhonObject()
		{
			_metaModel = MetadataCache<ErewhonObjectMetadata>.GetData(null);
		}
		public ErewhonObject() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public ErewhonObject(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(ErewhonObject), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected ErewhonObject(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass, params System.Object[] parameters) :
			base(lifetime, type, metaClass, parameters)
		{
			this._initialize();
		}
	}

	public partial class ErewhonObjectMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		private ErewhonObjectMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public ErewhonObjectMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(ErewhonObject), "ErewhonObject", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
		}
	}
}
