//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(ItemsByNumberDict))]
	public partial class ItemsByNumberDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _codeNumber = MetadataCache<ItemsByNumberDictMetadata>.GetData(null).CodeNumberKey;

		public ItemsByNumberDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_codeNumber})
		{
		}

		public ItemsByNumberDictKey(Int32 codeNumber) :
				this()
		{
			this.CodeNumber = codeNumber;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("codeNumber", 0, typeof(Int32), Length = 4, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public Int32 CodeNumber
		{
			get
			{
				return ((Int32)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Item))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemsByNumberDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemsByNumberDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ItemsByNumberDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "ItemsByNumberDict", typeof(MemberKeyDictionary<ItemsByNumberDictKey, Item>), MembershipType=typeof(Item), Keys="codeNumber")]
	public partial class ItemsByNumberDict : MemberKeyDictionary<ItemsByNumberDictKey, Item>
	{

		private static ItemsByNumberDictMetadata _metaModel;

		partial void Initialize();


		static ItemsByNumberDict()
		{
			_metaModel = MetadataCache<ItemsByNumberDictMetadata>.GetData(null);
		}

		public ItemsByNumberDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public ItemsByNumberDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(ItemsByNumberDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected ItemsByNumberDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual Item this[Int32 codeNumber]
		{
			get
			{
				ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
				 return base[_key_];
			}
			set
			{
				ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(Int32 codeNumber, out Item value)
		{
			ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(Int32 codeNumber, JadeSoftware.Joob.SearchStrategy strategy, out Item value)
		{
			ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<ItemsByNumberDictKey, Item> StartingAtKey(Int32 codeNumber)
		{
			ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<ItemsByNumberDictKey, Item> StartingAtKey(Int32 codeNumber, JadeSoftware.Joob.SearchStrategy strategy)
		{
			ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(Int32 codeNumber, Item value)
		{
			ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(Int32 codeNumber, Item value)
		{
			ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(Int32 codeNumber, Item value)
		{
			ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(Int32 codeNumber)
		{
			ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
			base.Remove(_key_);
		}

		public virtual void Remove(Int32 codeNumber, Item member)
		{
			ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
			base.Remove(_key_, member);
		}

		public virtual Item TryRemove(Int32 codeNumber)
		{
			ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(Int32 codeNumber, Item member)
		{
			ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(Int32 codeNumber, Item member)
		{
			ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(Int32 codeNumber)
		{
			ItemsByNumberDictKey _key_ = new ItemsByNumberDictKey(codeNumber);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Item))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemsByNumberDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemsByNumberDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ItemsByNumberDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class ItemsByNumberDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : Item
	{

		private static ItemsByNumberDictMetadata _metaModel;

		partial void Initialize();


		static ItemsByNumberDict()
		{
			_metaModel = MetadataCache<ItemsByNumberDictMetadata>.GetData(null);
		}

		protected ItemsByNumberDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class ItemsByNumberDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata CodeNumberKey;

		private ItemsByNumberDictMetadata()
		{
		}

		public ItemsByNumberDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(ItemsByNumberDict), "ItemsByNumberDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.CodeNumberKey = metaClass.CheckMemberKey(typeof(ItemsByNumberDict), typeof(Item), "codeNumber", typeof(Int32), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
