//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(ItemCategoriesByNameDict))]
	public partial class ItemCategoriesByNameDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _name = MetadataCache<ItemCategoriesByNameDictMetadata>.GetData(null).NameKey;

		public ItemCategoriesByNameDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_name})
		{
		}

		public ItemCategoriesByNameDictKey(String name) :
				this()
		{
			this.Name = name;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("name", 0, typeof(String), Length = 40, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String Name
		{
			get
			{
				return ((String)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategory))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategoriesByNameDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemCategoriesByNameDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ItemCategoriesByNameDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "ItemCategoriesByNameDict", typeof(MemberKeyDictionary<ItemCategoriesByNameDictKey, ItemCategory>), MembershipType=typeof(ItemCategory), Keys="name")]
	public partial class ItemCategoriesByNameDict : MemberKeyDictionary<ItemCategoriesByNameDictKey, ItemCategory>
	{

		private static ItemCategoriesByNameDictMetadata _metaModel;

		partial void Initialize();


		static ItemCategoriesByNameDict()
		{
			_metaModel = MetadataCache<ItemCategoriesByNameDictMetadata>.GetData(null);
		}

		public ItemCategoriesByNameDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public ItemCategoriesByNameDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(ItemCategoriesByNameDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected ItemCategoriesByNameDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual ItemCategory this[String name]
		{
			get
			{
				ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
				 return base[_key_];
			}
			set
			{
				ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(String name, out ItemCategory value)
		{
			ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(String name, JadeSoftware.Joob.SearchStrategy strategy, out ItemCategory value)
		{
			ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<ItemCategoriesByNameDictKey, ItemCategory> StartingAtKey(String name)
		{
			ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<ItemCategoriesByNameDictKey, ItemCategory> StartingAtKey(String name, JadeSoftware.Joob.SearchStrategy strategy)
		{
			ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(String name, ItemCategory value)
		{
			ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(String name, ItemCategory value)
		{
			ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(String name, ItemCategory value)
		{
			ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(String name)
		{
			ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
			base.Remove(_key_);
		}

		public virtual void Remove(String name, ItemCategory member)
		{
			ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
			base.Remove(_key_, member);
		}

		public virtual ItemCategory TryRemove(String name)
		{
			ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(String name, ItemCategory member)
		{
			ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(String name, ItemCategory member)
		{
			ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(String name)
		{
			ItemCategoriesByNameDictKey _key_ = new ItemCategoriesByNameDictKey(name);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategory))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategoriesByNameDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemCategoriesByNameDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ItemCategoriesByNameDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class ItemCategoriesByNameDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : ItemCategory
	{

		private static ItemCategoriesByNameDictMetadata _metaModel;

		partial void Initialize();


		static ItemCategoriesByNameDict()
		{
			_metaModel = MetadataCache<ItemCategoriesByNameDictMetadata>.GetData(null);
		}

		protected ItemCategoriesByNameDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class ItemCategoriesByNameDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata NameKey;

		private ItemCategoriesByNameDictMetadata()
		{
		}

		public ItemCategoriesByNameDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(ItemCategoriesByNameDict), "ItemCategoriesByNameDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.NameKey = metaClass.CheckMemberKey(typeof(ItemCategoriesByNameDict), typeof(ItemCategory), "name", typeof(String), 40, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
