//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(ItemCategoriesByPrefixDict))]
	public partial class ItemCategoriesByPrefixDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _prefix = MetadataCache<ItemCategoriesByPrefixDictMetadata>.GetData(null).PrefixKey;

		public ItemCategoriesByPrefixDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_prefix})
		{
		}

		public ItemCategoriesByPrefixDictKey(String prefix) :
				this()
		{
			this.Prefix = prefix;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("prefix", 0, typeof(String), Length = 4, CaseSensitive = false, Ascending = true, SortOrder = -1)]
		public String Prefix
		{
			get
			{
				return ((String)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategory))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategoriesByPrefixDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemCategoriesByPrefixDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ItemCategoriesByPrefixDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "ItemCategoriesByPrefixDict", typeof(MemberKeyDictionary<ItemCategoriesByPrefixDictKey, ItemCategory>), MembershipType=typeof(ItemCategory), Keys="prefix")]
	public partial class ItemCategoriesByPrefixDict : MemberKeyDictionary<ItemCategoriesByPrefixDictKey, ItemCategory>
	{

		private static ItemCategoriesByPrefixDictMetadata _metaModel;

		partial void Initialize();


		static ItemCategoriesByPrefixDict()
		{
			_metaModel = MetadataCache<ItemCategoriesByPrefixDictMetadata>.GetData(null);
		}

		public ItemCategoriesByPrefixDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public ItemCategoriesByPrefixDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(ItemCategoriesByPrefixDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected ItemCategoriesByPrefixDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual ItemCategory this[String prefix]
		{
			get
			{
				ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
				 return base[_key_];
			}
			set
			{
				ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(String prefix, out ItemCategory value)
		{
			ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(String prefix, JadeSoftware.Joob.SearchStrategy strategy, out ItemCategory value)
		{
			ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<ItemCategoriesByPrefixDictKey, ItemCategory> StartingAtKey(String prefix)
		{
			ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<ItemCategoriesByPrefixDictKey, ItemCategory> StartingAtKey(String prefix, JadeSoftware.Joob.SearchStrategy strategy)
		{
			ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(String prefix, ItemCategory value)
		{
			ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(String prefix, ItemCategory value)
		{
			ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(String prefix, ItemCategory value)
		{
			ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(String prefix)
		{
			ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
			base.Remove(_key_);
		}

		public virtual void Remove(String prefix, ItemCategory member)
		{
			ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
			base.Remove(_key_, member);
		}

		public virtual ItemCategory TryRemove(String prefix)
		{
			ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(String prefix, ItemCategory member)
		{
			ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(String prefix, ItemCategory member)
		{
			ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(String prefix)
		{
			ItemCategoriesByPrefixDictKey _key_ = new ItemCategoriesByPrefixDictKey(prefix);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategory))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategoriesByPrefixDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemCategoriesByPrefixDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ItemCategoriesByPrefixDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class ItemCategoriesByPrefixDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : ItemCategory
	{

		private static ItemCategoriesByPrefixDictMetadata _metaModel;

		partial void Initialize();


		static ItemCategoriesByPrefixDict()
		{
			_metaModel = MetadataCache<ItemCategoriesByPrefixDictMetadata>.GetData(null);
		}

		protected ItemCategoriesByPrefixDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class ItemCategoriesByPrefixDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata PrefixKey;

		private ItemCategoriesByPrefixDictMetadata()
		{
		}

		public ItemCategoriesByPrefixDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(ItemCategoriesByPrefixDict), "ItemCategoriesByPrefixDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.PrefixKey = metaClass.CheckMemberKey(typeof(ItemCategoriesByPrefixDict), typeof(ItemCategory), "prefix", typeof(String), 4, JadeSoftware.Joob.CaseSensitivityOption.Insensitive, JadeSoftware.Joob.KeyOrderOption.Ascending, -1);
		}
	}
}
