//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(ItemsByPrefixByNumberDict))]
	public partial class ItemsByPrefixByNumberDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _myItemCategory_prefix = MetadataCache<ItemsByPrefixByNumberDictMetadata>.GetData(null).MyItemCategory_prefixKey;
		private static JadeSoftware.Joob.KeyMetadata _codeNumber = MetadataCache<ItemsByPrefixByNumberDictMetadata>.GetData(null).CodeNumberKey;

		public ItemsByPrefixByNumberDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_myItemCategory_prefix,
					_codeNumber})
		{
		}

		public ItemsByPrefixByNumberDictKey(String myItemCategory_prefix, Int32 codeNumber) :
				this()
		{
			this.MyItemCategory_prefix = myItemCategory_prefix;
			this.CodeNumber = codeNumber;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("myItemCategory_prefix", 0, typeof(String), Length = 4, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String MyItemCategory_prefix
		{
			get
			{
				return ((String)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("codeNumber", 1, typeof(Int32), Length = 4, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public Int32 CodeNumber
		{
			get
			{
				return ((Int32)(this.Keys[1]));
			}
			set
			{
				this.Keys[1] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Item))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemsByPrefixByNumberDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemsByPrefixByNumberDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ItemsByPrefixByNumberDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "ItemsByPrefixByNumberDict", typeof(MemberKeyDictionary<ItemsByPrefixByNumberDictKey, Item>), MembershipType=typeof(Item), Keys="myItemCategory_prefix;codeNumber")]
	public partial class ItemsByPrefixByNumberDict : MemberKeyDictionary<ItemsByPrefixByNumberDictKey, Item>
	{

		private static ItemsByPrefixByNumberDictMetadata _metaModel;

		partial void Initialize();


		static ItemsByPrefixByNumberDict()
		{
			_metaModel = MetadataCache<ItemsByPrefixByNumberDictMetadata>.GetData(null);
		}

		public ItemsByPrefixByNumberDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public ItemsByPrefixByNumberDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(ItemsByPrefixByNumberDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected ItemsByPrefixByNumberDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual Item this[String myItemCategory_prefix, Int32 codeNumber]
		{
			get
			{
				ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
				 return base[_key_];
			}
			set
			{
				ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(String myItemCategory_prefix, Int32 codeNumber, out Item value)
		{
			ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(String myItemCategory_prefix, Int32 codeNumber, JadeSoftware.Joob.SearchStrategy strategy, out Item value)
		{
			ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<ItemsByPrefixByNumberDictKey, Item> StartingAtKey(String myItemCategory_prefix, Int32 codeNumber)
		{
			ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<ItemsByPrefixByNumberDictKey, Item> StartingAtKey(String myItemCategory_prefix, Int32 codeNumber, JadeSoftware.Joob.SearchStrategy strategy)
		{
			ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(String myItemCategory_prefix, Int32 codeNumber, Item value)
		{
			ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(String myItemCategory_prefix, Int32 codeNumber, Item value)
		{
			ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(String myItemCategory_prefix, Int32 codeNumber, Item value)
		{
			ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(String myItemCategory_prefix, Int32 codeNumber)
		{
			ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
			base.Remove(_key_);
		}

		public virtual void Remove(String myItemCategory_prefix, Int32 codeNumber, Item member)
		{
			ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
			base.Remove(_key_, member);
		}

		public virtual Item TryRemove(String myItemCategory_prefix, Int32 codeNumber)
		{
			ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(String myItemCategory_prefix, Int32 codeNumber, Item member)
		{
			ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(String myItemCategory_prefix, Int32 codeNumber, Item member)
		{
			ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(String myItemCategory_prefix, Int32 codeNumber)
		{
			ItemsByPrefixByNumberDictKey _key_ = new ItemsByPrefixByNumberDictKey(myItemCategory_prefix, codeNumber);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Item))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemsByPrefixByNumberDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemsByPrefixByNumberDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ItemsByPrefixByNumberDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class ItemsByPrefixByNumberDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : Item
	{

		private static ItemsByPrefixByNumberDictMetadata _metaModel;

		partial void Initialize();


		static ItemsByPrefixByNumberDict()
		{
			_metaModel = MetadataCache<ItemsByPrefixByNumberDictMetadata>.GetData(null);
		}

		protected ItemsByPrefixByNumberDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class ItemsByPrefixByNumberDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata MyItemCategory_prefixKey;

		internal JadeSoftware.Joob.KeyMetadata CodeNumberKey;

		private ItemsByPrefixByNumberDictMetadata()
		{
		}

		public ItemsByPrefixByNumberDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(ItemsByPrefixByNumberDict), "ItemsByPrefixByNumberDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.MyItemCategory_prefixKey = metaClass.CheckMemberKey(typeof(ItemsByPrefixByNumberDict), typeof(ItemCategory), "prefix", typeof(String), 4, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending, String.Empty, "myItemCategory");
			this.CodeNumberKey = metaClass.CheckMemberKey(typeof(ItemsByPrefixByNumberDict), typeof(Item), "codeNumber", typeof(Int32), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
