//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(ItemsByCategoryPrefixDict))]
	public partial class ItemsByCategoryPrefixDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _myItemCategory = MetadataCache<ItemsByCategoryPrefixDictMetadata>.GetData(null).MyItemCategoryKey;
		private static JadeSoftware.Joob.KeyMetadata _myItemCategory_prefix = MetadataCache<ItemsByCategoryPrefixDictMetadata>.GetData(null).MyItemCategory_prefixKey;
		private static JadeSoftware.Joob.KeyMetadata _codeNumber = MetadataCache<ItemsByCategoryPrefixDictMetadata>.GetData(null).CodeNumberKey;

		public ItemsByCategoryPrefixDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_myItemCategory,
					_myItemCategory_prefix,
					_codeNumber})
		{
		}

		public ItemsByCategoryPrefixDictKey(ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber) :
				this()
		{
			this.MyItemCategory = myItemCategory;
			this.MyItemCategory_prefix = myItemCategory_prefix;
			this.CodeNumber = codeNumber;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("myItemCategory", 0, typeof(ItemCategory), Length = 12, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public ItemCategory MyItemCategory
		{
			get
			{
				return ((ItemCategory)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("myItemCategory_prefix", 1, typeof(String), Length = 4, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String MyItemCategory_prefix
		{
			get
			{
				return ((String)(this.Keys[1]));
			}
			set
			{
				this.Keys[1] = value;
			}
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("codeNumber", 2, typeof(Int32), Length = 4, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public Int32 CodeNumber
		{
			get
			{
				return ((Int32)(this.Keys[2]));
			}
			set
			{
				this.Keys[2] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategory))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Item))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemsByCategoryPrefixDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemsByCategoryPrefixDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ItemsByCategoryPrefixDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "ItemsByCategoryPrefixDict", typeof(MemberKeyDictionary<ItemsByCategoryPrefixDictKey, Item>), MembershipType=typeof(Item), Keys="myItemCategory;myItemCategory_prefix;codeNumber")]
	public partial class ItemsByCategoryPrefixDict : MemberKeyDictionary<ItemsByCategoryPrefixDictKey, Item>
	{

		private static ItemsByCategoryPrefixDictMetadata _metaModel;

		partial void Initialize();


		static ItemsByCategoryPrefixDict()
		{
			_metaModel = MetadataCache<ItemsByCategoryPrefixDictMetadata>.GetData(null);
		}

		public ItemsByCategoryPrefixDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public ItemsByCategoryPrefixDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(ItemsByCategoryPrefixDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected ItemsByCategoryPrefixDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual Item this[ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber]
		{
			get
			{
				ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
				 return base[_key_];
			}
			set
			{
				ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber, out Item value)
		{
			ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber, JadeSoftware.Joob.SearchStrategy strategy, out Item value)
		{
			ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<ItemsByCategoryPrefixDictKey, Item> StartingAtKey(ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber)
		{
			ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<ItemsByCategoryPrefixDictKey, Item> StartingAtKey(ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber, JadeSoftware.Joob.SearchStrategy strategy)
		{
			ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber, Item value)
		{
			ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber, Item value)
		{
			ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber, Item value)
		{
			ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber)
		{
			ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
			base.Remove(_key_);
		}

		public virtual void Remove(ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber, Item member)
		{
			ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
			base.Remove(_key_, member);
		}

		public virtual Item TryRemove(ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber)
		{
			ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber, Item member)
		{
			ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber, Item member)
		{
			ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(ItemCategory myItemCategory, String myItemCategory_prefix, Int32 codeNumber)
		{
			ItemsByCategoryPrefixDictKey _key_ = new ItemsByCategoryPrefixDictKey(myItemCategory, myItemCategory_prefix, codeNumber);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategory))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Item))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemsByCategoryPrefixDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemsByCategoryPrefixDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ItemsByCategoryPrefixDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class ItemsByCategoryPrefixDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : Item
	{

		private static ItemsByCategoryPrefixDictMetadata _metaModel;

		partial void Initialize();


		static ItemsByCategoryPrefixDict()
		{
			_metaModel = MetadataCache<ItemsByCategoryPrefixDictMetadata>.GetData(null);
		}

		protected ItemsByCategoryPrefixDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class ItemsByCategoryPrefixDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata MyItemCategoryKey;

		internal JadeSoftware.Joob.KeyMetadata MyItemCategory_prefixKey;

		internal JadeSoftware.Joob.KeyMetadata CodeNumberKey;

		private ItemsByCategoryPrefixDictMetadata()
		{
		}

		public ItemsByCategoryPrefixDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			MetadataCache<ItemCategoryMetadata>.LoadData(null);
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(ItemsByCategoryPrefixDict), "ItemsByCategoryPrefixDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.MyItemCategoryKey = metaClass.CheckMemberKey(typeof(ItemsByCategoryPrefixDict), typeof(Item), "myItemCategory", typeof(ItemCategory), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
			this.MyItemCategory_prefixKey = metaClass.CheckMemberKey(typeof(ItemsByCategoryPrefixDict), typeof(ItemCategory), "prefix", typeof(String), 4, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending, String.Empty, "myItemCategory");
			this.CodeNumberKey = metaClass.CheckMemberKey(typeof(ItemsByCategoryPrefixDict), typeof(Item), "codeNumber", typeof(Int32), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
