//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemsByNumberDict))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemCategoryMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ItemCategory", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "ItemCategory", typeof(PersistentModel))]
	public partial class ItemCategory : PersistentModel
	{
		private static ItemCategoryMetadata _metaModel;
		partial void _initialize();
		static ItemCategory()
		{
			_metaModel = MetadataCache<ItemCategoryMetadata>.GetData(null);
		}
		public ItemCategory() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public ItemCategory(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(ItemCategory), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected ItemCategory(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass, params System.Object[] parameters) :
			base(lifetime, type, metaClass, parameters)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allItems", typeof(ItemsByNumberDict), DatabaseTypeName="ItemsByNumberDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public ItemsByNumberDict AllItems
		{
			get
			{
				return this.GetPropertyReference<ItemsByNumberDict>(_metaModel.metaClass, _metaModel.allItems);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("description", typeof(String), DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Description
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.description);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.description, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("name", typeof(String), Length=40, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Name
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.name);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.name, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("prefix", typeof(String), Length=4, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Prefix
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.prefix);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.prefix, value);
			}
		}
	#endregion
	}

	public partial class ItemCategoryMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata allItems;
		internal JadeSoftware.Joob.PropertyMetadata description;
		internal JadeSoftware.Joob.PropertyMetadata name;
		internal JadeSoftware.Joob.PropertyMetadata prefix;

		private ItemCategoryMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public ItemCategoryMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(ItemCategory), "ItemCategory", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			allItems = metaClass.CheckProperty("allItems", typeof(ItemsByNumberDict));
			description = metaClass.CheckProperty("description", typeof(String));
			name = metaClass.CheckProperty("name", typeof(String), 40);
			prefix = metaClass.CheckProperty("prefix", typeof(String), 4);
		}
	}
}
