//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Address))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Agent))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Client))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CommissionRate))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Company))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Country))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Item))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemCategory))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Location))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Region))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailItem))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Tender))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderItem))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(PersistentModelMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("PersistentModel", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "PersistentModel", typeof(JoobObject))]
	public partial class PersistentModel : JoobObject
	{
		private static PersistentModelMetadata _metaModel;
		partial void _initialize();
		static PersistentModel()
		{
			_metaModel = MetadataCache<PersistentModelMetadata>.GetData(null);
		}
		public PersistentModel() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public PersistentModel(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(PersistentModel), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected PersistentModel(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass, params System.Object[] parameters) :
			base(lifetime, type, metaClass, parameters)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("guid", typeof(String), Length=38, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Guid
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.guid);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.guid, value);
			}
		}
	#endregion
	}

	public partial class PersistentModelMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata guid;

		private PersistentModelMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public PersistentModelMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(PersistentModel), "PersistentModel", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			guid = metaClass.CheckProperty("guid", typeof(String), 38);
		}
	}
}
