//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(RetailSalesByTimeItemDict))]
	public partial class RetailSalesByTimeItemDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _dateSold = MetadataCache<RetailSalesByTimeItemDictMetadata>.GetData(null).DateSoldKey;
		private static JadeSoftware.Joob.KeyMetadata _myItem_myItemCategory_prefix = MetadataCache<RetailSalesByTimeItemDictMetadata>.GetData(null).MyItem_myItemCategory_prefixKey;
		private static JadeSoftware.Joob.KeyMetadata _myItem_codeNumber = MetadataCache<RetailSalesByTimeItemDictMetadata>.GetData(null).MyItem_codeNumberKey;

		public RetailSalesByTimeItemDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_dateSold,
					_myItem_myItemCategory_prefix,
					_myItem_codeNumber})
		{
		}

		public RetailSalesByTimeItemDictKey(DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber) :
				this()
		{
			this.DateSold = dateSold;
			this.MyItem_myItemCategory_prefix = myItem_myItemCategory_prefix;
			this.MyItem_codeNumber = myItem_codeNumber;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("dateSold", 0, typeof(DateTime), Length = 8, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public DateTime DateSold
		{
			get
			{
				return ((DateTime)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("myItem_myItemCategory_prefix", 1, typeof(String), Length = 4, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String MyItem_myItemCategory_prefix
		{
			get
			{
				return ((String)(this.Keys[1]));
			}
			set
			{
				this.Keys[1] = value;
			}
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("myItem_codeNumber", 2, typeof(Int32), Length = 4, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public Int32 MyItem_codeNumber
		{
			get
			{
				return ((Int32)(this.Keys[2]));
			}
			set
			{
				this.Keys[2] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailSale))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailSalesByTimeItemDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(RetailSalesByTimeItemDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("RetailSalesByTimeItemDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "RetailSalesByTimeItemDict", typeof(MemberKeyDictionary<RetailSalesByTimeItemDictKey, RetailSale>), MembershipType=typeof(RetailSale), Keys="dateSold;myItem_myItemCategory_prefix;myItem_codeNumber")]
	public partial class RetailSalesByTimeItemDict : MemberKeyDictionary<RetailSalesByTimeItemDictKey, RetailSale>
	{

		private static RetailSalesByTimeItemDictMetadata _metaModel;

		partial void Initialize();


		static RetailSalesByTimeItemDict()
		{
			_metaModel = MetadataCache<RetailSalesByTimeItemDictMetadata>.GetData(null);
		}

		public RetailSalesByTimeItemDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public RetailSalesByTimeItemDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(RetailSalesByTimeItemDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected RetailSalesByTimeItemDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual RetailSale this[DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber]
		{
			get
			{
				RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
				 return base[_key_];
			}
			set
			{
				RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber, out RetailSale value)
		{
			RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber, JadeSoftware.Joob.SearchStrategy strategy, out RetailSale value)
		{
			RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<RetailSalesByTimeItemDictKey, RetailSale> StartingAtKey(DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber)
		{
			RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<RetailSalesByTimeItemDictKey, RetailSale> StartingAtKey(DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber, JadeSoftware.Joob.SearchStrategy strategy)
		{
			RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber, RetailSale value)
		{
			RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber, RetailSale value)
		{
			RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber, RetailSale value)
		{
			RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber)
		{
			RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
			base.Remove(_key_);
		}

		public virtual void Remove(DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber, RetailSale member)
		{
			RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
			base.Remove(_key_, member);
		}

		public virtual RetailSale TryRemove(DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber)
		{
			RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber, RetailSale member)
		{
			RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber, RetailSale member)
		{
			RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(DateTime dateSold, String myItem_myItemCategory_prefix, Int32 myItem_codeNumber)
		{
			RetailSalesByTimeItemDictKey _key_ = new RetailSalesByTimeItemDictKey(dateSold, myItem_myItemCategory_prefix, myItem_codeNumber);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailSale))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailSalesByTimeItemDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(RetailSalesByTimeItemDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("RetailSalesByTimeItemDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class RetailSalesByTimeItemDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : RetailSale
	{

		private static RetailSalesByTimeItemDictMetadata _metaModel;

		partial void Initialize();


		static RetailSalesByTimeItemDict()
		{
			_metaModel = MetadataCache<RetailSalesByTimeItemDictMetadata>.GetData(null);
		}

		protected RetailSalesByTimeItemDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class RetailSalesByTimeItemDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata DateSoldKey;

		internal JadeSoftware.Joob.KeyMetadata MyItem_myItemCategory_prefixKey;

		internal JadeSoftware.Joob.KeyMetadata MyItem_codeNumberKey;

		private RetailSalesByTimeItemDictMetadata()
		{
		}

		public RetailSalesByTimeItemDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(RetailSalesByTimeItemDict), "RetailSalesByTimeItemDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.DateSoldKey = metaClass.CheckMemberKey(typeof(RetailSalesByTimeItemDict), typeof(RetailSale), "dateSold", typeof(DateTime), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
			this.MyItem_myItemCategory_prefixKey = metaClass.CheckMemberKey(typeof(RetailSalesByTimeItemDict), typeof(ItemCategory), "prefix", typeof(String), 4, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending, String.Empty, "myItem.myItemCategory");
			this.MyItem_codeNumberKey = metaClass.CheckMemberKey(typeof(RetailSalesByTimeItemDict), typeof(Item), "codeNumber", typeof(Int32), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending, String.Empty, "myItem");
		}
	}
}
