//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(RetailItemsByGUIDDict))]
	public partial class RetailItemsByGUIDDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _guid = MetadataCache<RetailItemsByGUIDDictMetadata>.GetData(null).GuidKey;

		public RetailItemsByGUIDDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_guid})
		{
		}

		public RetailItemsByGUIDDictKey(String guid) :
				this()
		{
			this.Guid = guid;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("guid", 0, typeof(String), Length = 38, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String Guid
		{
			get
			{
				return ((String)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailItem))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailItemsByGUIDDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(RetailItemsByGUIDDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("RetailItemsByGUIDDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "RetailItemsByGUIDDict", typeof(MemberKeyDictionary<RetailItemsByGUIDDictKey, RetailItem>), MembershipType=typeof(RetailItem), Keys="guid")]
	public partial class RetailItemsByGUIDDict : MemberKeyDictionary<RetailItemsByGUIDDictKey, RetailItem>
	{

		private static RetailItemsByGUIDDictMetadata _metaModel;

		partial void Initialize();


		static RetailItemsByGUIDDict()
		{
			_metaModel = MetadataCache<RetailItemsByGUIDDictMetadata>.GetData(null);
		}

		public RetailItemsByGUIDDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public RetailItemsByGUIDDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(RetailItemsByGUIDDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected RetailItemsByGUIDDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual RetailItem this[String guid]
		{
			get
			{
				RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
				 return base[_key_];
			}
			set
			{
				RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(String guid, out RetailItem value)
		{
			RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(String guid, JadeSoftware.Joob.SearchStrategy strategy, out RetailItem value)
		{
			RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<RetailItemsByGUIDDictKey, RetailItem> StartingAtKey(String guid)
		{
			RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<RetailItemsByGUIDDictKey, RetailItem> StartingAtKey(String guid, JadeSoftware.Joob.SearchStrategy strategy)
		{
			RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(String guid, RetailItem value)
		{
			RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(String guid, RetailItem value)
		{
			RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(String guid, RetailItem value)
		{
			RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(String guid)
		{
			RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
			base.Remove(_key_);
		}

		public virtual void Remove(String guid, RetailItem member)
		{
			RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
			base.Remove(_key_, member);
		}

		public virtual RetailItem TryRemove(String guid)
		{
			RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(String guid, RetailItem member)
		{
			RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(String guid, RetailItem member)
		{
			RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(String guid)
		{
			RetailItemsByGUIDDictKey _key_ = new RetailItemsByGUIDDictKey(guid);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailItem))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailItemsByGUIDDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(RetailItemsByGUIDDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("RetailItemsByGUIDDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class RetailItemsByGUIDDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : RetailItem
	{

		private static RetailItemsByGUIDDictMetadata _metaModel;

		partial void Initialize();


		static RetailItemsByGUIDDict()
		{
			_metaModel = MetadataCache<RetailItemsByGUIDDictMetadata>.GetData(null);
		}

		protected RetailItemsByGUIDDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class RetailItemsByGUIDDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata GuidKey;

		private RetailItemsByGUIDDictMetadata()
		{
		}

		public RetailItemsByGUIDDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(RetailItemsByGUIDDict), "RetailItemsByGUIDDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.GuidKey = metaClass.CheckMemberKey(typeof(RetailItemsByGUIDDict), typeof(RetailItem), "guid", typeof(String), 38, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
