//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(TendersByOfferTimeDict))]
	public partial class TendersByOfferTimeDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _offer = MetadataCache<TendersByOfferTimeDictMetadata>.GetData(null).OfferKey;
		private static JadeSoftware.Joob.KeyMetadata _dateTendered = MetadataCache<TendersByOfferTimeDictMetadata>.GetData(null).DateTenderedKey;

		public TendersByOfferTimeDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_offer,
					_dateTendered})
		{
		}

		public TendersByOfferTimeDictKey(Decimal offer, DateTime dateTendered) :
				this()
		{
			this.Offer = offer;
			this.DateTendered = dateTendered;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("offer", 0, typeof(Decimal), Length = 12, CaseSensitive = true, Ascending = false, SortOrder = 0, Precision = 12, Scale = 2)]
		public Decimal Offer
		{
			get
			{
				return ((Decimal)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("dateTendered", 1, typeof(DateTime), Length = 8, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public DateTime DateTendered
		{
			get
			{
				return ((DateTime)(this.Keys[1]));
			}
			set
			{
				this.Keys[1] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Tender))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TendersByOfferTimeDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(TendersByOfferTimeDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("TendersByOfferTimeDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "TendersByOfferTimeDict", typeof(MemberKeyDictionary<TendersByOfferTimeDictKey, Tender>), MembershipType=typeof(Tender), Keys="offer;dateTendered")]
	public partial class TendersByOfferTimeDict : MemberKeyDictionary<TendersByOfferTimeDictKey, Tender>
	{

		private static TendersByOfferTimeDictMetadata _metaModel;

		partial void Initialize();


		static TendersByOfferTimeDict()
		{
			_metaModel = MetadataCache<TendersByOfferTimeDictMetadata>.GetData(null);
		}

		public TendersByOfferTimeDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public TendersByOfferTimeDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(TendersByOfferTimeDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected TendersByOfferTimeDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual Tender this[Decimal offer, DateTime dateTendered]
		{
			get
			{
				TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
				 return base[_key_];
			}
			set
			{
				TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(Decimal offer, DateTime dateTendered, out Tender value)
		{
			TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(Decimal offer, DateTime dateTendered, JadeSoftware.Joob.SearchStrategy strategy, out Tender value)
		{
			TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<TendersByOfferTimeDictKey, Tender> StartingAtKey(Decimal offer, DateTime dateTendered)
		{
			TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<TendersByOfferTimeDictKey, Tender> StartingAtKey(Decimal offer, DateTime dateTendered, JadeSoftware.Joob.SearchStrategy strategy)
		{
			TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(Decimal offer, DateTime dateTendered, Tender value)
		{
			TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(Decimal offer, DateTime dateTendered, Tender value)
		{
			TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(Decimal offer, DateTime dateTendered, Tender value)
		{
			TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(Decimal offer, DateTime dateTendered)
		{
			TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
			base.Remove(_key_);
		}

		public virtual void Remove(Decimal offer, DateTime dateTendered, Tender member)
		{
			TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
			base.Remove(_key_, member);
		}

		public virtual Tender TryRemove(Decimal offer, DateTime dateTendered)
		{
			TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(Decimal offer, DateTime dateTendered, Tender member)
		{
			TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(Decimal offer, DateTime dateTendered, Tender member)
		{
			TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(Decimal offer, DateTime dateTendered)
		{
			TendersByOfferTimeDictKey _key_ = new TendersByOfferTimeDictKey(offer, dateTendered);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Tender))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TendersByOfferTimeDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(TendersByOfferTimeDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("TendersByOfferTimeDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class TendersByOfferTimeDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : Tender
	{

		private static TendersByOfferTimeDictMetadata _metaModel;

		partial void Initialize();


		static TendersByOfferTimeDict()
		{
			_metaModel = MetadataCache<TendersByOfferTimeDictMetadata>.GetData(null);
		}

		protected TendersByOfferTimeDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class TendersByOfferTimeDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata OfferKey;

		internal JadeSoftware.Joob.KeyMetadata DateTenderedKey;

		private TendersByOfferTimeDictMetadata()
		{
		}

		public TendersByOfferTimeDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(TendersByOfferTimeDict), "TendersByOfferTimeDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.OfferKey = metaClass.CheckMemberKey(typeof(TendersByOfferTimeDict), typeof(Tender), "offer", typeof(Decimal), 12, 2, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Descending);
			this.DateTenderedKey = metaClass.CheckMemberKey(typeof(TendersByOfferTimeDict), typeof(Tender), "dateTendered", typeof(DateTime), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
