//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TendersByOfferTimeDict))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TendersByTimeOfferDict))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(TenderItemMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("TenderItem", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "TenderItem", typeof(Item))]
	public partial class TenderItem : Item
	{
		private static TenderItemMetadata _metaModel;
		partial void _initialize();
		static TenderItem()
		{
			_metaModel = MetadataCache<TenderItemMetadata>.GetData(null);
		}
		public TenderItem() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public TenderItem(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(TenderItem), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected TenderItem(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass, params System.Object[] parameters) :
			base(lifetime, type, metaClass, parameters)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allTendersByOfferTime", typeof(TendersByOfferTimeDict), DatabaseTypeName="TendersByOfferTimeDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public TendersByOfferTimeDict AllTendersByOfferTime
		{
			get
			{
				return this.GetPropertyReference<TendersByOfferTimeDict>(_metaModel.metaClass, _metaModel.allTendersByOfferTime);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("allTendersByTimeOffer", typeof(TendersByTimeOfferDict), DatabaseTypeName="TendersByTimeOfferDict")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public TendersByTimeOfferDict AllTendersByTimeOffer
		{
			get
			{
				return this.GetPropertyReference<TendersByTimeOfferDict>(_metaModel.metaClass, _metaModel.allTendersByTimeOffer);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("closureDate", typeof(DateTime), DatabaseTypeName="Date")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public DateTime ClosureDate
		{
			get
			{
				return this.GetPropertyDate(_metaModel.metaClass, _metaModel.closureDate);
			}
			set
			{
				this.SetPropertyDate(_metaModel.metaClass, _metaModel.closureDate, value);
			}
		}
	#endregion
	}

	public partial class TenderItemMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata allTendersByOfferTime;
		internal JadeSoftware.Joob.PropertyMetadata allTendersByTimeOffer;
		internal JadeSoftware.Joob.PropertyMetadata closureDate;

		private TenderItemMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public TenderItemMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(TenderItem), "TenderItem", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			allTendersByOfferTime = metaClass.CheckProperty("allTendersByOfferTime", typeof(TendersByOfferTimeDict));
			allTendersByTimeOffer = metaClass.CheckProperty("allTendersByTimeOffer", typeof(TendersByTimeOfferDict));
			closureDate = metaClass.CheckProperty("closureDate", typeof(DateTime));
		}
	}
}
