//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Client))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Company))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderItem))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderSale))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(TenderMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("Tender", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "Tender", typeof(PersistentModel))]
	public partial class Tender : PersistentModel
	{
		private static TenderMetadata _metaModel;
		partial void _initialize();
		static Tender()
		{
			_metaModel = MetadataCache<TenderMetadata>.GetData(null);
		}
		public Tender() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public Tender(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(Tender), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected Tender(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass, params System.Object[] parameters) :
			base(lifetime, type, metaClass, parameters)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("dateTendered", typeof(DateTime), DatabaseTypeName="TimeStamp")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public DateTime DateTendered
		{
			get
			{
				return this.GetPropertyTimestamp(_metaModel.metaClass, _metaModel.dateTendered);
			}
			set
			{
				this.SetPropertyTimestamp(_metaModel.metaClass, _metaModel.dateTendered, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myClient", typeof(Client), DatabaseTypeName="Client")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Client MyClient
		{
			get
			{
				return this.GetPropertyReference<Client>(_metaModel.metaClass, _metaModel.myClient);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myClient, value, false);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myCompany", typeof(Company), DatabaseTypeName="Company")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Company MyCompany
		{
			get
			{
				return this.GetPropertyReference<Company>(_metaModel.metaClass, _metaModel.myCompany);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myCompany, value, false);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myTenderItem", typeof(TenderItem), DatabaseTypeName="TenderItem")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public TenderItem MyTenderItem
		{
			get
			{
				return this.GetPropertyReference<TenderItem>(_metaModel.metaClass, _metaModel.myTenderItem);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myTenderItem, value, false);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myTenderSale", typeof(TenderSale), DatabaseTypeName="TenderSale")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public TenderSale MyTenderSale
		{
			get
			{
				return this.GetPropertyReference<TenderSale>(_metaModel.metaClass, _metaModel.myTenderSale);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myTenderSale, value, true);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("offer", typeof(Decimal), Precision=12, Scale=2, DatabaseTypeName="Decimal")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Decimal Offer
		{
			get
			{
				return this.GetPropertyDecimal(_metaModel.metaClass, _metaModel.offer);
			}
			set
			{
				this.SetPropertyDecimal(_metaModel.metaClass, _metaModel.offer, value);
			}
		}
	#endregion
	}

	public partial class TenderMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata dateTendered;
		internal JadeSoftware.Joob.PropertyMetadata myClient;
		internal JadeSoftware.Joob.PropertyMetadata myCompany;
		internal JadeSoftware.Joob.PropertyMetadata myTenderItem;
		internal JadeSoftware.Joob.PropertyMetadata myTenderSale;
		internal JadeSoftware.Joob.PropertyMetadata offer;

		private TenderMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public TenderMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(Tender), "Tender", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			dateTendered = metaClass.CheckProperty("dateTendered", typeof(DateTime));
			myClient = metaClass.CheckProperty("myClient", typeof(Client));
			myCompany = metaClass.CheckProperty("myCompany", typeof(Company));
			myTenderItem = metaClass.CheckProperty("myTenderItem", typeof(TenderItem));
			myTenderSale = metaClass.CheckProperty("myTenderSale", typeof(TenderSale));
			offer = metaClass.CheckProperty("offer", typeof(Decimal), 12, 2);
		}
	}
}
