//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(TendersByItemTimeOfferDict))]
	public partial class TendersByItemTimeOfferDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _myTenderItem_myItemCategory_prefix = MetadataCache<TendersByItemTimeOfferDictMetadata>.GetData(null).MyTenderItem_myItemCategory_prefixKey;
		private static JadeSoftware.Joob.KeyMetadata _myTenderItem_codeNumber = MetadataCache<TendersByItemTimeOfferDictMetadata>.GetData(null).MyTenderItem_codeNumberKey;
		private static JadeSoftware.Joob.KeyMetadata _dateTendered = MetadataCache<TendersByItemTimeOfferDictMetadata>.GetData(null).DateTenderedKey;
		private static JadeSoftware.Joob.KeyMetadata _offer = MetadataCache<TendersByItemTimeOfferDictMetadata>.GetData(null).OfferKey;

		public TendersByItemTimeOfferDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_myTenderItem_myItemCategory_prefix,
					_myTenderItem_codeNumber,
					_dateTendered,
					_offer})
		{
		}

		public TendersByItemTimeOfferDictKey(String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer) :
				this()
		{
			this.MyTenderItem_myItemCategory_prefix = myTenderItem_myItemCategory_prefix;
			this.MyTenderItem_codeNumber = myTenderItem_codeNumber;
			this.DateTendered = dateTendered;
			this.Offer = offer;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("myTenderItem_myItemCategory_prefix", 0, typeof(String), Length = 4, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String MyTenderItem_myItemCategory_prefix
		{
			get
			{
				return ((String)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("myTenderItem_codeNumber", 1, typeof(Int32), Length = 4, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public Int32 MyTenderItem_codeNumber
		{
			get
			{
				return ((Int32)(this.Keys[1]));
			}
			set
			{
				this.Keys[1] = value;
			}
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("dateTendered", 2, typeof(DateTime), Length = 8, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public DateTime DateTendered
		{
			get
			{
				return ((DateTime)(this.Keys[2]));
			}
			set
			{
				this.Keys[2] = value;
			}
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("offer", 3, typeof(Decimal), Length = 12, CaseSensitive = true, Ascending = false, SortOrder = 0, Precision = 12, Scale = 2)]
		public Decimal Offer
		{
			get
			{
				return ((Decimal)(this.Keys[3]));
			}
			set
			{
				this.Keys[3] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Tender))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TendersByItemTimeOfferDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(TendersByItemTimeOfferDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("TendersByItemTimeOfferDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "TendersByItemTimeOfferDict", typeof(MemberKeyDictionary<TendersByItemTimeOfferDictKey, Tender>), MembershipType=typeof(Tender), Keys="myTenderItem_myItemCategory_prefix;myTenderItem_codeNumber;dateTendered;offer")]
	public partial class TendersByItemTimeOfferDict : MemberKeyDictionary<TendersByItemTimeOfferDictKey, Tender>
	{

		private static TendersByItemTimeOfferDictMetadata _metaModel;

		partial void Initialize();


		static TendersByItemTimeOfferDict()
		{
			_metaModel = MetadataCache<TendersByItemTimeOfferDictMetadata>.GetData(null);
		}

		public TendersByItemTimeOfferDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public TendersByItemTimeOfferDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(TendersByItemTimeOfferDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected TendersByItemTimeOfferDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual Tender this[String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer]
		{
			get
			{
				TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
				 return base[_key_];
			}
			set
			{
				TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer, out Tender value)
		{
			TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer, JadeSoftware.Joob.SearchStrategy strategy, out Tender value)
		{
			TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<TendersByItemTimeOfferDictKey, Tender> StartingAtKey(String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer)
		{
			TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<TendersByItemTimeOfferDictKey, Tender> StartingAtKey(String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer, JadeSoftware.Joob.SearchStrategy strategy)
		{
			TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer, Tender value)
		{
			TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer, Tender value)
		{
			TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer, Tender value)
		{
			TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer)
		{
			TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
			base.Remove(_key_);
		}

		public virtual void Remove(String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer, Tender member)
		{
			TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
			base.Remove(_key_, member);
		}

		public virtual Tender TryRemove(String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer)
		{
			TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer, Tender member)
		{
			TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer, Tender member)
		{
			TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(String myTenderItem_myItemCategory_prefix, Int32 myTenderItem_codeNumber, DateTime dateTendered, Decimal offer)
		{
			TendersByItemTimeOfferDictKey _key_ = new TendersByItemTimeOfferDictKey(myTenderItem_myItemCategory_prefix, myTenderItem_codeNumber, dateTendered, offer);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Tender))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TendersByItemTimeOfferDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(TendersByItemTimeOfferDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("TendersByItemTimeOfferDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class TendersByItemTimeOfferDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : Tender
	{

		private static TendersByItemTimeOfferDictMetadata _metaModel;

		partial void Initialize();


		static TendersByItemTimeOfferDict()
		{
			_metaModel = MetadataCache<TendersByItemTimeOfferDictMetadata>.GetData(null);
		}

		protected TendersByItemTimeOfferDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class TendersByItemTimeOfferDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata MyTenderItem_myItemCategory_prefixKey;

		internal JadeSoftware.Joob.KeyMetadata MyTenderItem_codeNumberKey;

		internal JadeSoftware.Joob.KeyMetadata DateTenderedKey;

		internal JadeSoftware.Joob.KeyMetadata OfferKey;

		private TendersByItemTimeOfferDictMetadata()
		{
		}

		public TendersByItemTimeOfferDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(TendersByItemTimeOfferDict), "TendersByItemTimeOfferDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.MyTenderItem_myItemCategory_prefixKey = metaClass.CheckMemberKey(typeof(TendersByItemTimeOfferDict), typeof(ItemCategory), "prefix", typeof(String), 4, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending, String.Empty, "myTenderItem.myItemCategory");
			this.MyTenderItem_codeNumberKey = metaClass.CheckMemberKey(typeof(TendersByItemTimeOfferDict), typeof(TenderItem), "codeNumber", typeof(Int32), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending, String.Empty, "myTenderItem");
			this.DateTenderedKey = metaClass.CheckMemberKey(typeof(TendersByItemTimeOfferDict), typeof(Tender), "dateTendered", typeof(DateTime), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
			this.OfferKey = metaClass.CheckMemberKey(typeof(TendersByItemTimeOfferDict), typeof(Tender), "offer", typeof(Decimal), 12, 2, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Descending);
		}
	}
}
