//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(TenderItemsBySaleDateCodeDict))]
	public partial class TenderItemsBySaleDateCodeDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _mySale = MetadataCache<TenderItemsBySaleDateCodeDictMetadata>.GetData(null).MySaleKey;
		private static JadeSoftware.Joob.KeyMetadata _closureDate = MetadataCache<TenderItemsBySaleDateCodeDictMetadata>.GetData(null).ClosureDateKey;
		private static JadeSoftware.Joob.KeyMetadata _myItemCategory_prefix = MetadataCache<TenderItemsBySaleDateCodeDictMetadata>.GetData(null).MyItemCategory_prefixKey;
		private static JadeSoftware.Joob.KeyMetadata _codeNumber = MetadataCache<TenderItemsBySaleDateCodeDictMetadata>.GetData(null).CodeNumberKey;

		public TenderItemsBySaleDateCodeDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_mySale,
					_closureDate,
					_myItemCategory_prefix,
					_codeNumber})
		{
		}

		public TenderItemsBySaleDateCodeDictKey(Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber) :
				this()
		{
			this.MySale = mySale;
			this.ClosureDate = closureDate;
			this.MyItemCategory_prefix = myItemCategory_prefix;
			this.CodeNumber = codeNumber;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("mySale", 0, typeof(Sale), Length = 12, CaseSensitive = true, Ascending = false, SortOrder = 0)]
		public Sale MySale
		{
			get
			{
				return ((Sale)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("closureDate", 1, typeof(DateTime), Length = 4, CaseSensitive = true, Ascending = false, SortOrder = 0)]
		public DateTime ClosureDate
		{
			get
			{
				return ((DateTime)(this.Keys[1]));
			}
			set
			{
				this.Keys[1] = value;
			}
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("myItemCategory_prefix", 2, typeof(String), Length = 4, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String MyItemCategory_prefix
		{
			get
			{
				return ((String)(this.Keys[2]));
			}
			set
			{
				this.Keys[2] = value;
			}
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("codeNumber", 3, typeof(Int32), Length = 4, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public Int32 CodeNumber
		{
			get
			{
				return ((Int32)(this.Keys[3]));
			}
			set
			{
				this.Keys[3] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Sale))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderItem))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderItemsBySaleDateCodeDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(TenderItemsBySaleDateCodeDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("TenderItemsBySaleDateCodeDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "TenderItemsBySaleDateCodeDict", typeof(MemberKeyDictionary<TenderItemsBySaleDateCodeDictKey, TenderItem>), MembershipType=typeof(TenderItem), Keys="mySale;closureDate;myItemCategory_prefix;codeNumber")]
	public partial class TenderItemsBySaleDateCodeDict : MemberKeyDictionary<TenderItemsBySaleDateCodeDictKey, TenderItem>
	{

		private static TenderItemsBySaleDateCodeDictMetadata _metaModel;

		partial void Initialize();


		static TenderItemsBySaleDateCodeDict()
		{
			_metaModel = MetadataCache<TenderItemsBySaleDateCodeDictMetadata>.GetData(null);
		}

		public TenderItemsBySaleDateCodeDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public TenderItemsBySaleDateCodeDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(TenderItemsBySaleDateCodeDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected TenderItemsBySaleDateCodeDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual TenderItem this[Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber]
		{
			get
			{
				TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
				 return base[_key_];
			}
			set
			{
				TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber, out TenderItem value)
		{
			TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber, JadeSoftware.Joob.SearchStrategy strategy, out TenderItem value)
		{
			TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<TenderItemsBySaleDateCodeDictKey, TenderItem> StartingAtKey(Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber)
		{
			TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<TenderItemsBySaleDateCodeDictKey, TenderItem> StartingAtKey(Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber, JadeSoftware.Joob.SearchStrategy strategy)
		{
			TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber, TenderItem value)
		{
			TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber, TenderItem value)
		{
			TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber, TenderItem value)
		{
			TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber)
		{
			TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
			base.Remove(_key_);
		}

		public virtual void Remove(Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber, TenderItem member)
		{
			TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
			base.Remove(_key_, member);
		}

		public virtual TenderItem TryRemove(Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber)
		{
			TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber, TenderItem member)
		{
			TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber, TenderItem member)
		{
			TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(Sale mySale, DateTime closureDate, String myItemCategory_prefix, Int32 codeNumber)
		{
			TenderItemsBySaleDateCodeDictKey _key_ = new TenderItemsBySaleDateCodeDictKey(mySale, closureDate, myItemCategory_prefix, codeNumber);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Sale))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderItem))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderItemsBySaleDateCodeDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(TenderItemsBySaleDateCodeDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("TenderItemsBySaleDateCodeDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class TenderItemsBySaleDateCodeDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : TenderItem
	{

		private static TenderItemsBySaleDateCodeDictMetadata _metaModel;

		partial void Initialize();


		static TenderItemsBySaleDateCodeDict()
		{
			_metaModel = MetadataCache<TenderItemsBySaleDateCodeDictMetadata>.GetData(null);
		}

		protected TenderItemsBySaleDateCodeDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class TenderItemsBySaleDateCodeDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata MySaleKey;

		internal JadeSoftware.Joob.KeyMetadata ClosureDateKey;

		internal JadeSoftware.Joob.KeyMetadata MyItemCategory_prefixKey;

		internal JadeSoftware.Joob.KeyMetadata CodeNumberKey;

		private TenderItemsBySaleDateCodeDictMetadata()
		{
		}

		public TenderItemsBySaleDateCodeDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			MetadataCache<SaleMetadata>.LoadData(null);
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(TenderItemsBySaleDateCodeDict), "TenderItemsBySaleDateCodeDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.MySaleKey = metaClass.CheckMemberKey(typeof(TenderItemsBySaleDateCodeDict), typeof(TenderItem), "mySale", typeof(Sale), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Descending);
			this.ClosureDateKey = metaClass.CheckMemberKey(typeof(TenderItemsBySaleDateCodeDict), typeof(TenderItem), "closureDate", typeof(DateTime), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Descending);
			this.MyItemCategory_prefixKey = metaClass.CheckMemberKey(typeof(TenderItemsBySaleDateCodeDict), typeof(ItemCategory), "prefix", typeof(String), 4, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending, String.Empty, "myItemCategory");
			this.CodeNumberKey = metaClass.CheckMemberKey(typeof(TenderItemsBySaleDateCodeDict), typeof(TenderItem), "codeNumber", typeof(Int32), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
