//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(TendersByTimeOfferDict))]
	public partial class TendersByTimeOfferDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _dateTendered = MetadataCache<TendersByTimeOfferDictMetadata>.GetData(null).DateTenderedKey;
		private static JadeSoftware.Joob.KeyMetadata _offer = MetadataCache<TendersByTimeOfferDictMetadata>.GetData(null).OfferKey;

		public TendersByTimeOfferDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_dateTendered,
					_offer})
		{
		}

		public TendersByTimeOfferDictKey(DateTime dateTendered, Decimal offer) :
				this()
		{
			this.DateTendered = dateTendered;
			this.Offer = offer;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("dateTendered", 0, typeof(DateTime), Length = 8, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public DateTime DateTendered
		{
			get
			{
				return ((DateTime)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("offer", 1, typeof(Decimal), Length = 12, CaseSensitive = true, Ascending = false, SortOrder = 0, Precision = 12, Scale = 2)]
		public Decimal Offer
		{
			get
			{
				return ((Decimal)(this.Keys[1]));
			}
			set
			{
				this.Keys[1] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Tender))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TendersByTimeOfferDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(TendersByTimeOfferDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("TendersByTimeOfferDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "TendersByTimeOfferDict", typeof(MemberKeyDictionary<TendersByTimeOfferDictKey, Tender>), MembershipType=typeof(Tender), Keys="dateTendered;offer")]
	public partial class TendersByTimeOfferDict : MemberKeyDictionary<TendersByTimeOfferDictKey, Tender>
	{

		private static TendersByTimeOfferDictMetadata _metaModel;

		partial void Initialize();


		static TendersByTimeOfferDict()
		{
			_metaModel = MetadataCache<TendersByTimeOfferDictMetadata>.GetData(null);
		}

		public TendersByTimeOfferDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public TendersByTimeOfferDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(TendersByTimeOfferDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected TendersByTimeOfferDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual Tender this[DateTime dateTendered, Decimal offer]
		{
			get
			{
				TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
				 return base[_key_];
			}
			set
			{
				TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(DateTime dateTendered, Decimal offer, out Tender value)
		{
			TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(DateTime dateTendered, Decimal offer, JadeSoftware.Joob.SearchStrategy strategy, out Tender value)
		{
			TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<TendersByTimeOfferDictKey, Tender> StartingAtKey(DateTime dateTendered, Decimal offer)
		{
			TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<TendersByTimeOfferDictKey, Tender> StartingAtKey(DateTime dateTendered, Decimal offer, JadeSoftware.Joob.SearchStrategy strategy)
		{
			TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(DateTime dateTendered, Decimal offer, Tender value)
		{
			TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(DateTime dateTendered, Decimal offer, Tender value)
		{
			TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(DateTime dateTendered, Decimal offer, Tender value)
		{
			TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(DateTime dateTendered, Decimal offer)
		{
			TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
			base.Remove(_key_);
		}

		public virtual void Remove(DateTime dateTendered, Decimal offer, Tender member)
		{
			TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
			base.Remove(_key_, member);
		}

		public virtual Tender TryRemove(DateTime dateTendered, Decimal offer)
		{
			TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(DateTime dateTendered, Decimal offer, Tender member)
		{
			TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(DateTime dateTendered, Decimal offer, Tender member)
		{
			TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(DateTime dateTendered, Decimal offer)
		{
			TendersByTimeOfferDictKey _key_ = new TendersByTimeOfferDictKey(dateTendered, offer);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Tender))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TendersByTimeOfferDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(TendersByTimeOfferDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("TendersByTimeOfferDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class TendersByTimeOfferDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : Tender
	{

		private static TendersByTimeOfferDictMetadata _metaModel;

		partial void Initialize();


		static TendersByTimeOfferDict()
		{
			_metaModel = MetadataCache<TendersByTimeOfferDictMetadata>.GetData(null);
		}

		protected TendersByTimeOfferDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class TendersByTimeOfferDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata DateTenderedKey;

		internal JadeSoftware.Joob.KeyMetadata OfferKey;

		private TendersByTimeOfferDictMetadata()
		{
		}

		public TendersByTimeOfferDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(TendersByTimeOfferDict), "TendersByTimeOfferDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.DateTenderedKey = metaClass.CheckMemberKey(typeof(TendersByTimeOfferDict), typeof(Tender), "dateTendered", typeof(DateTime), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
			this.OfferKey = metaClass.CheckMemberKey(typeof(TendersByTimeOfferDict), typeof(Tender), "offer", typeof(Decimal), 12, 2, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Descending);
		}
	}
}
