//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 22.0.03
//      Generation date : Tuesday, 27 February 2024
//      Generated by    : cnwth3
//      JADE Schema     : ErehwhonExternalInterfacesSchema
//      Exposure Name   : ErewhonExposures
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace ErewhonExposures
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(TenderItemsByGUIDDict))]
	public partial class TenderItemsByGUIDDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _guid = MetadataCache<TenderItemsByGUIDDictMetadata>.GetData(null).GuidKey;

		public TenderItemsByGUIDDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_guid})
		{
		}

		public TenderItemsByGUIDDictKey(String guid) :
				this()
		{
			this.Guid = guid;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("guid", 0, typeof(String), Length = 38, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String Guid
		{
			get
			{
				return ((String)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderItem))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderItemsByGUIDDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(TenderItemsByGUIDDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("TenderItemsByGUIDDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace = "ErewhonExposures", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "TenderItemsByGUIDDict", typeof(MemberKeyDictionary<TenderItemsByGUIDDictKey, TenderItem>), MembershipType=typeof(TenderItem), Keys="guid")]
	public partial class TenderItemsByGUIDDict : MemberKeyDictionary<TenderItemsByGUIDDictKey, TenderItem>
	{

		private static TenderItemsByGUIDDictMetadata _metaModel;

		partial void Initialize();


		static TenderItemsByGUIDDict()
		{
			_metaModel = MetadataCache<TenderItemsByGUIDDictMetadata>.GetData(null);
		}

		public TenderItemsByGUIDDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public TenderItemsByGUIDDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(TenderItemsByGUIDDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected TenderItemsByGUIDDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual TenderItem this[String guid]
		{
			get
			{
				TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
				 return base[_key_];
			}
			set
			{
				TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(String guid, out TenderItem value)
		{
			TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(String guid, JadeSoftware.Joob.SearchStrategy strategy, out TenderItem value)
		{
			TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<TenderItemsByGUIDDictKey, TenderItem> StartingAtKey(String guid)
		{
			TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<TenderItemsByGUIDDictKey, TenderItem> StartingAtKey(String guid, JadeSoftware.Joob.SearchStrategy strategy)
		{
			TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(String guid, TenderItem value)
		{
			TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(String guid, TenderItem value)
		{
			TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(String guid, TenderItem value)
		{
			TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(String guid)
		{
			TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
			base.Remove(_key_);
		}

		public virtual void Remove(String guid, TenderItem member)
		{
			TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
			base.Remove(_key_, member);
		}

		public virtual TenderItem TryRemove(String guid)
		{
			TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(String guid, TenderItem member)
		{
			TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(String guid, TenderItem member)
		{
			TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(String guid)
		{
			TenderItemsByGUIDDictKey _key_ = new TenderItemsByGUIDDictKey(guid);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderItem))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(TenderItemsByGUIDDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(TenderItemsByGUIDDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("TenderItemsByGUIDDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", ClassNamespace="ErewhonExposures")]
	public abstract partial class TenderItemsByGUIDDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : TenderItem
	{

		private static TenderItemsByGUIDDictMetadata _metaModel;

		partial void Initialize();


		static TenderItemsByGUIDDict()
		{
			_metaModel = MetadataCache<TenderItemsByGUIDDictMetadata>.GetData(null);
		}

		protected TenderItemsByGUIDDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class TenderItemsByGUIDDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata GuidKey;

		private TenderItemsByGUIDDictMetadata()
		{
		}

		public TenderItemsByGUIDDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(TenderItemsByGUIDDict), "TenderItemsByGUIDDict", "RootSchema.CardSchema.ErewhonBaseSchema.ErewhonModelSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.GuidKey = metaClass.CheckMemberKey(typeof(TenderItemsByGUIDDict), typeof(TenderItem), "guid", typeof(String), 38, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
